### PR TITLE
Flatten

### PR DESCRIPTION
**Pull request by LeonFedotov**
still missing docs, gonna add after lunch

### CODE REVIEW

**Comment by LeonFedotov** [comment]
Found some edge cases gonna fiz after lunch as well, do not merge.

**Comment by avi** [comment]
Please only support flatten of Array of Arrays not a mix of arrays and non arrays.
And optimizing needs to use setOnArray when updating otherwise transformations that consume the output won't trigger. You can add a test that does flatten->map and see that it will not work as expected

**Comment by LeonFedotov** [comment]
@avi good points, on it.

**Comment by LeonFedotov** [comment]
@avi done, take a peek :)

**Comment by LeonFedotov** [comment]
@avi hey, ive added a test and im not sure about the failue, take a look when you can, ive added the most naive implementation of flatten and its weird im getting different  results: `root.map(v=>v).flatten()` isnt the same as  `root.flatten()` and im not sure why...

**Comment by LeonFedotov** [comment]
@avi take a look, i think its done... (some flaky tests on bolt pervent this from passing for me locally currently running it in ci https://github.com/wix-private/bolt/pull/1935)

**Comment by LeonFedotov** [comment]
@avi its done, take a look? :)

**Pull request merged**
