### PR TITLE
add support for String.split(String)

### PR DESCRIPTION
**Pull request by EtaiG**
Regular expressions is more complex.
It looks like carmi doesn't know what to do to invalidate the cache.
I tried to resolve it but after ~20 min gave up - can come back to handle RegExp if there's a use case for it

### CODE REVIEW

**Comment by avi** [comment]
because you're creating an array it will cause a new array to be created every time it runs (string changes) I'd rather create an array and copy the split into it (a bit like assign/defaults - if you want a reference)

**Comment by EtaiG** [comment]
ok, I'll take a look

**Comment by EtaiG** [comment]
@avi I would need to invalidate array on string change if it would change array length?

**Comment by avi** [comment]
The problem is that if you map/filter on the result you would get a new
map/filter array too and it could cascade and invalidate a lot more than
you expected.
You can leave it this way, I need to change the caching semantics in
optimizing anyway which would make it not a problem.

**Pull request merged**
