### PR TITLE
Remove topLevel self-closed comment after argument for non-debug mode.

### PR DESCRIPTION
**Pull request by yavorsky**
Let's reduce the output size and remove comments we have `$topLevel[Int /* ... */]` if no debug option was added.

It also takes additional time to compile the project when parsing all nodes (via webpack for example).
Moreover, after babel compiled the carmi code with `compact: true` and removed all new lines, it makes acorn very slow b/c it's trying to find the location of each node with bypassing comments:
https://github.com/acornjs/acorn/blob/172309446319efd9302d0bb6effc2ce7e9189f7b/acorn/src/tokenize.js#L107

`require('acorn').parse(carmiOutput, { locations: true }) // A lot of time`

cc @avi @LeonFedotov

### CODE REVIEW

**Comment by LeonFedotov** [comment]
Hello, thank you for your contribution! 
What in your opinion would be the best way to test your addition and see the improvement in compile time?
Thanks again!

**Comment by yavorsky** [comment]
@LeonFedotov
I think it's not carmi area of responsibility to test compilation time of Webpack or check for acorn performance while parsing carmi output. But we can test and control output content in general.

I've extended the PR a bit:
 - [Added support for babel-plugin-macros config](https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/user.md#config-experimental). Here I see 2 good points: It would be good to allow macros users configure debug mode and it's good for us so we can test ouput according to mode and create different snapshots.
- [Here I added additional test for debug mode](https://github.com/wix-incubator/carmi/pull/210/files#diff-4aea2154cb164903e283c4ef1acebe07) that mocks config and creates a snapshot.
- [Updated version to be static for babel-plugin-macros](https://github.com/wix-incubator/carmi/pull/210/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L42), since for next minor update it supports babel@7.

**Comment by LeonFedotov** [comment]
Hey @yavorsky, thanks for your comment and tests, sorry about the silence - I'm currently testing the compile times and intend to merge this by the end of the day.
Cheers!

**Comment by LeonFedotov** [comment]
Im seeing a 60s(!!!) improvement :+1: Good job! @yavorsky :D

**Pull request merged**
